name: step_one
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # google_maps_flutter: ^2.0.12
  # location: ^4.3.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/step_one_logo.png


  